# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.8.2.dev0+g15ecfb5.d20230212"
__version_tuple__ = version_tuple = (0, 8, 2, "dev0", "g15ecfb5.d20230212")
